---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: "{{remote_user}}"
  become: yes
  roles:
    - common
    - ufw
    - mariadb
    - nginx
    - postfix
    - php-fpm
    - redis
    - wordpress
    - webgrind
    - backup
    - sftp
    - newrelic
