---
- name: Install utilities
  apt: 
    name:
      - vim
      - git
      - subversion
      - unzip
      - python-pip
      - python-dev
      - build-essential
    state: latest
    update_cache: yes

- name: Set timezone variables
  copy: content="{{ timezone }}"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone
